### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by dumbelldore** [jmiemirza/LaFTer#1]
Great work!
In the paper its mentioned that you used "a single GPU cluster consisting of 4 NVIDIA Quadro Graphic Cards", can I know the memory specification of the GPUs. Would it be possible to train using a single GPU of 24gb?

**Comment by jmiemirza** [comment]
Hope you figured it out. But generally, it should work out. We list the entire compute (on the server) used for the experiments in the supplementary. Many experiments were also performed on a single 3090 with 24gb. 

Best Mirza.

**Comment by dumbelldore** [comment]
Hey, yeah I figured it out. But I have a weird issue. Training doesn't work on a single gpu node, it only works on multi gpu node, even though it only uses one of the gpu.
When I run on a single GPU machine, I get the following error 
`RuntimeError: No CUDA GPUs are available`
Any idea why this might be happening?

**Comment by jmiemirza** [comment]
Hi, 

Unfortunately, I haven't experienced this. Hope you found a solution.

**Comment by fazliimam** [comment]
Hey @dumbelldore change `CUDA_VISIBLE_DEVICES=1` to `CUDA_VISIBLE_DEVICES=0` in lafter.sh file

**Comment by dumbelldore** [comment]
Yeah this was the issue, thanks @fazlicodes
