### ISSUE TITLE
Prompts to generate text dataset for Eurosat dataset

### ISSUE THREAD

**Issue by fazliimam** [jmiemirza/LaFTer#2]
Great work!
Can I know what was the prompts used to generate the text dataset for Eurosat?

**Comment by jmiemirza** [comment]
Hi, 

Thanks for your interest. Please find the prompts here: https://github.com/jmiemirza/LaFTer/blob/master/descriptions/generic_descriptions.py

Best,
Mirza

**Comment by fazliimam** [comment]
Hey Mirza,
Thank you for responding.
But for eurosat, the text datasets start with:
`A satellite photo of <>...`
`A <class> can be identified in a satellite photo...`
`To identify the satellite photo of a <>...`

So I assume you used different templates as compared to the ones used in other datasets

**Comment by jmiemirza** [comment]
I do not completely understand the assumption, but as far as I remember (from the time of the creation of this dataset), the prompts should be the same for all as in the script. 

Best,
Mirza.

**Comment by fazliimam** [comment]
So the templates in the https://github.com/jmiemirza/LaFTer/blob/master/descriptions/generic_descriptions.py would have produced this version for EuroSat text dataset (https://github.com/jmiemirza/LaFTer/blob/master/descriptions/generic/EuroSAT_old.json) and for the version https://github.com/jmiemirza/LaFTer/blob/master/descriptions/generic/EuroSAT.json I assume different prompts were used?
Is it not the case?

**Comment by jmiemirza** [comment]
Sorry for the confusion. Since multiple projects were going on in the same codebase, the descriptions might have merged. I will clean up the repo. 

But you should use EuroSat.json -- EuroSAT_old is depreciated. 

As far as the prompts are concerned. They should be same for all datasets.

**Comment by fazliimam** [comment]
Noted, thank you
