### ISSUE TITLE
Reason for adding noise for text classifier training in stage 1 and data augmentation for in stage 2

### ISSUE THREAD

**Issue by dumbelldore** [jmiemirza/LaFTer#3]
Hi, thank you for making the code available. Could you please be kind enough answer my questions?
> What is the reason behind adding noise when training the text classifier?
> What is the reason behind augmenting the image when its being sent to the prompted vision encoder?

**Comment by jmiemirza** [comment]
Hi,

I appreciate your interest. 

1. The added noise is a regularizer to avoid overfitting of the text classifier. 
2. I can refer you to fixmatch paper: https://arxiv.org/abs/2001.07685

Best,
Mirza.
