### ISSUE TITLE
Code for TSNE Projection

### ISSUE THREAD

**Issue by fazliimam** [jmiemirza/LaFTer#4]
Hi, is it possible to obtain the code to generate the TSNE projections listed in the paper?

**Comment by jmiemirza** [comment]
Hi, I cannot find the saved embeddings or the original code at the moment, but it was pretty standard TSNE plot with Scikit: https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html

**Comment by fazliimam** [comment]
Ah...okay, thanks
