### ISSUE TITLE
When reproduce main table results, use of template ensemble

### ISSUE THREAD

**Issue by ChoiDae1** [jmiemirza/LaFTer#6]
Hello!
Currently, I'm interested in your works. 
When reporting zero-shot accuracy in main tables, did you use template ensemble? or only use one template 'a photo of a {}'  at inference? 

Thank you.

**Comment by jmiemirza** [comment]
Hi, thanks for your interest. To get these baselines, we follow the codebase from CoOp (https://arxiv.org/abs/2109.01134). 

They use the simple prompt template: 'A photo of a {}'

Best Mirza.
