### ISSUE TITLE
Dataset segmentation

### ISSUE THREAD

**Issue by yichenwang231** [jmiemirza/LaFTer#7]
Hi, very nice work,
 I would like to know that except for the ImageNet-A,ImageNet-S and ImageNet-R, is the ratio of training, validation and testing for all other datasets 5:2:3?

**Comment by jmiemirza** [comment]
Hi, thank you for your interest. For all other datasets, we follow the splits provided by CoOp (https://arxiv.org/abs/2109.01134) in their codebase. Please refer to their paper and the codebase for details. 

Best Mirza.
